from PyQt5 import QtCore, QtGui, QtWidgets
from db import DB
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow) -> None:
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1124, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_speak = QtWidgets.QPushButton(self.centralwidget)
        self.btn_speak.setGeometry(QtCore.QRect(140, 80, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn_speak.setFont(font)
        self.btn_speak.setObjectName("btn_speak")
        self.btn_speak.setStyleSheet("background : lightblue;")
        self.btn_validate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_validate.setGeometry(QtCore.QRect(620, 80, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.btn_validate.setFont(font)
        self.btn_validate.setObjectName("btn_validate")
        self.btn_validate.setStyleSheet("background : lightblue;")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 220, 1121, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_scramble = QtWidgets.QWidget()
        self.tab_scramble.setObjectName("tab_scramble")
        self.label_1 = QtWidgets.QLabel(self.tab_scramble)
        self.label_1.setGeometry(QtCore.QRect(130, 50, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_scramble = QtWidgets.QLabel(self.tab_scramble)
        self.label_scramble.setGeometry(QtCore.QRect(70, 120,600,100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_scramble.setFont(font)
        self.label_scramble.setText("")
        self.label_scramble.setAlignment(QtCore.Qt.AlignLeft)
        self.label_scramble.setObjectName("label_scramble")
        self.lineEdit_scramble = QtWidgets.QLineEdit(self.tab_scramble)
        self.lineEdit_scramble.setGeometry(QtCore.QRect(260, 320, 631, 151))
        font = QtGui.QFont()
        font.setPointSize(65)
        self.lineEdit_scramble.setFont(font)
        self.lineEdit_scramble.setText("")
        self.lineEdit_scramble.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scramble.setObjectName("lineEdit_scramble")
        self.lineEdit_scramble.setStyleSheet("background : lightblue;")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_scramble)
        self.stackedWidget.setGeometry(QtCore.QRect(590, 120, 461, 80))
        self.stackedWidget.setObjectName("stackedWidget")
        self.tabWidget.addTab(self.tab_scramble, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.menubar.addAction(self.menuExit.menuAction())
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_speak.setText(_translate("MainWindow", "SPEAK"))
        self.btn_validate.setText(_translate("MainWindow", "Validate"))
        self.label_1.setText(_translate("MainWindow", "Scrambled Word"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scramble), _translate("MainWindow", "Word Scramble"))
        
class Ui_WordWindow(object):
    def GoBack(self) -> None:
        self.Start_stackedWidget.setCurrentIndex(0)
        self.lineEdit_word1.setText("")
        self.lineEdit_word2.setText("")
        self.lineEdit_word3.setText("")
        self.lineEdit_word4.setText("")
        self.lineEdit_word5.setText("")
        self.lineEdit_word6.setText("")
        self.lineEdit_word7.setText("")
        self.lineEdit_word8.setText("")
        self.lineEdit_word9.setText("")
        self.lineEdit_word10.setText("")
        

    def setupUi(self, WordWindow) -> None:
        WordWindow.setObjectName("WordWindow")
        WordWindow.resize(815, 686)
        self.centralwidget = QtWidgets.QWidget(WordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.Start_stackedWidget.setGeometry(QtCore.QRect(0, 0, 791, 621))
        self.Start_stackedWidget.setObjectName("Start_stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.btn_week1 = QtWidgets.QPushButton(self.page1)
        self.btn_week1.setGeometry(QtCore.QRect(190, 110, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week1.setFont(font)
        self.btn_week1.setObjectName("btn_week1")
        self.btn_week2 = QtWidgets.QPushButton(self.page1)
        self.btn_week2.setGeometry(QtCore.QRect(190, 220, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week2.setFont(font)
        self.btn_week2.setObjectName("btn_week2")
        self.btn_week3 = QtWidgets.QPushButton(self.page1)
        self.btn_week3.setGeometry(QtCore.QRect(190, 330, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week3.setFont(font)
        self.btn_week3.setObjectName("btn_week3")
        self.btn_week4 = QtWidgets.QPushButton(self.page1)
        self.btn_week4.setGeometry(QtCore.QRect(190, 440, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week4.setFont(font)
        self.btn_week4.setObjectName("btn_week4")
        self.btn_week5 = QtWidgets.QPushButton(self.page1)
        self.btn_week5.setGeometry(QtCore.QRect(190, 550, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week5.setFont(font)
        self.btn_week5.setObjectName("btn_week5")
        self.btn_week6 = QtWidgets.QPushButton(self.page1)
        self.btn_week6.setGeometry(QtCore.QRect(490, 110, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week6.setFont(font)
        self.btn_week6.setObjectName("btn_week6")
        self.btn_week7 = QtWidgets.QPushButton(self.page1)
        self.btn_week7.setGeometry(QtCore.QRect(490, 220, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week7.setFont(font)
        self.btn_week7.setObjectName("btn_week7")
        self.btn_week8 = QtWidgets.QPushButton(self.page1)
        self.btn_week8.setGeometry(QtCore.QRect(490, 330, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week8.setFont(font)
        self.btn_week8.setObjectName("btn_week8")
        self.btn_week9 = QtWidgets.QPushButton(self.page1)
        self.btn_week9.setGeometry(QtCore.QRect(490, 440, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week9.setFont(font)
        self.btn_week9.setObjectName("btn_week9")
        self.btn_week10 = QtWidgets.QPushButton(self.page1)
        self.btn_week10.setGeometry(QtCore.QRect(490, 550, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_week10.setFont(font)
        self.btn_week10.setObjectName("btn_week10")     
        self.Start_stackedWidget.addWidget(self.page1)
        self.btn_week1.setStyleSheet("background : lightblue;")
        self.btn_week2.setStyleSheet("background : lightblue;")
        self.btn_week3.setStyleSheet("background : lightblue;")
        self.btn_week4.setStyleSheet("background : lightblue;")
        self.btn_week5.setStyleSheet("background : lightblue;")
        self.btn_week6.setStyleSheet("background : lightblue;")
        self.btn_week7.setStyleSheet("background : lightblue;")
        self.btn_week8.setStyleSheet("background : lightblue;")
        self.btn_week9.setStyleSheet("background : lightblue;")
        self.btn_week10.setStyleSheet("background : lightblue;")
        
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_week = QtWidgets.QLabel(self.page2)
        self.label_week.setGeometry(QtCore.QRect(360, 50, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_week.setFont(font)
        self.label_week.setText("")
        self.label_week.setAlignment(QtCore.Qt.AlignCenter)
        self.label_week.setObjectName("label_week")
        self.lineEdit_word1 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word1.setGeometry(QtCore.QRect(110, 100, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word1.setFont(font)
        self.lineEdit_word1.setObjectName("lineEdit_word1")
        self.lineEdit_word2 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word2.setGeometry(QtCore.QRect(110, 200, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word2.setFont(font)
        self.lineEdit_word2.setObjectName("lineEdit_word2")
        self.lineEdit_word3 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word3.setGeometry(QtCore.QRect(110, 300, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word3.setFont(font)
        self.lineEdit_word3.setObjectName("lineEdit_word3")
        self.lineEdit_word4 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word4.setGeometry(QtCore.QRect(110, 400, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word4.setFont(font)
        self.lineEdit_word4.setObjectName("lineEdit_word4")
        self.lineEdit_word5 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word5.setGeometry(QtCore.QRect(110, 500, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word5.setFont(font)
        self.lineEdit_word5.setObjectName("lineEdit_word5")
        self.lineEdit_word6 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word6.setGeometry(QtCore.QRect(500, 100, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word6.setFont(font)
        self.lineEdit_word6.setObjectName("lineEdit_word6")
        self.lineEdit_word7 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word7.setGeometry(QtCore.QRect(500, 200, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word7.setFont(font)
        self.lineEdit_word7.setObjectName("lineEdit_word7")
        self.lineEdit_word8 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word8.setGeometry(QtCore.QRect(500, 300, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word8.setFont(font)
        self.lineEdit_word8.setObjectName("lineEdit_word8")
        self.lineEdit_word9 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word9.setGeometry(QtCore.QRect(500, 400, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word9.setFont(font)
        self.lineEdit_word9.setObjectName("lineEdit_word9")
        self.lineEdit_word10 = QtWidgets.QLineEdit(self.page2)
        self.lineEdit_word10.setGeometry(QtCore.QRect(500, 500, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_word10.setFont(font)
        self.lineEdit_word10.setObjectName("lineEdit_word10")
        self.btn_edit = QtWidgets.QPushButton(self.page2)
        self.btn_edit.setGeometry(QtCore.QRect(250, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.btn_edit.setStyleSheet("background : lightblue;")
        self.btn_back = QtWidgets.QPushButton(self.page2, clicked = lambda: self.GoBack())
        self.btn_back.setGeometry(QtCore.QRect(600, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.btn_back.setStyleSheet("background : lightblue;")
        self.btn_save = QtWidgets.QPushButton(self.page2)
        self.btn_save.setGeometry(QtCore.QRect(430, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setStyleSheet("background : lightblue;")
        self.btn_use = QtWidgets.QPushButton(self.page2)
        self.btn_use.setGeometry(QtCore.QRect(60, 570, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_use.setFont(font)
        self.btn_use.setObjectName("btn_use")
        self.btn_use.setStyleSheet("background : lightblue;")
        self.Start_stackedWidget.addWidget(self.page2)
        self.lineEdit_word1.setEnabled(False)
        self.lineEdit_word2.setEnabled(False)
        self.lineEdit_word3.setEnabled(False)
        self.lineEdit_word4.setEnabled(False)
        self.lineEdit_word5.setEnabled(False)
        self.lineEdit_word6.setEnabled(False)
        self.lineEdit_word7.setEnabled(False)
        self.lineEdit_word8.setEnabled(False)
        self.lineEdit_word9.setEnabled(False)
        self.lineEdit_word10.setEnabled(False)
        self.btn_save.setEnabled(False)

        WordWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WordWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 26))
        self.menubar.setObjectName("menubar")
        WordWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WordWindow)
        self.statusbar.setObjectName("statusbar")
        WordWindow.setStatusBar(self.statusbar)
        self.retranslateUi(WordWindow)
        self.Start_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WordWindow)

    def retranslateUi(self, WordWindow) -> None:
        _translate = QtCore.QCoreApplication.translate
        WordWindow.setWindowTitle(_translate("WordWindow", "Word Window"))
        self.btn_week1.setText(_translate("WordWindow", "Week 1"))
        self.btn_week2.setText(_translate("WordWindow", "Week 2"))
        self.btn_week3.setText(_translate("WordWindow", "Week 3"))
        self.btn_week4.setText(_translate("WordWindow", "Week 4"))
        self.btn_week5.setText(_translate("WordWindow", "Week 5"))
        self.btn_week6.setText(_translate("WordWindow", "Week 6"))
        self.btn_week7.setText(_translate("WordWindow", "Week 7"))
        self.btn_week8.setText(_translate("WordWindow", "Week 8"))
        self.btn_week9.setText(_translate("WordWindow", "Week 9"))
        self.btn_week10.setText(_translate("WordWindow", "Week 10"))
        self.btn_edit.setText(_translate("WordWindow", "Edit Words"))
        self.btn_save.setText(_translate("WordWindow", "Save Words"))
        self.btn_use.setText(_translate("WordWindow", "Use Words"))
        self.btn_back.setText(_translate("WordWindow", "Back"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    sys.exit(app.exec_())
